### PR TITLE
More Localization

### PR DESCRIPTION
**Pull request by urgiv**
correct "tooltip" to "Tooltip"
add few words
attempt to localize Agument names (praise regular expression, it makes things easier), I see the note message, but just tried
add zh-Hans

### CODE REVIEW

**Comment by urgiv** [comment]
the workshop localization link
https://github.com/urgiv/zh-Hans-localization-files-for-1.4.4-mods/blob/666966c2ad3e7f20b6fa3fd05d5aa872defa5127/workshop%20Title%20%26%20Description%20here/Weapon%20Augments/Simplified%20Chinese_workshop.txt

also, wonder whether u have plan to createa a discord channel for all these mods

**Review by BlockCrusader — APPROVED** [review]
Thanks for the continued localization work! Also great job on localizing the Augments, I really only made that note because I figured nobody would want to put in the effort to localize ALL of those names (I wouldn't want to for one).

As for a Discord, I have no plans for one. I imagine it'd be convenient for people with questions and stuff, but in all honesty having to go around answering bunches of questions from the community is the largest reason I was considering against public release in the first place. Is that selfish? Yes. However, all of these mods were made purely for the enjoyment of making mods, a passion project. I share them with the community - despite being made for myself - so others can freely enjoy the product if they want. While I do desire to ensure the quality of my work, I feel no obligation to run around and solve everyone's problems with the mods. 

Anyways, I'll try and get an update with this stuff out some time today (9/20/23)

**Comment by urgiv** [comment]
Localization for Simple Equipment Perks
https://github.com/urgiv/zh-Hans-localization-files-for-1.4.4-mods/commit/3bc25e7f2774cfa49483d6a1c6ed01edc3f42067

Btw, tml October update changes `Extra Jump API` and `NPCID.Sets.DebuffImmunitySets`, may cause issues to your mods.

**Comment by BlockCrusader** [comment]
Thx for the localization of Simple Equipment Perks. There is a GitHub page for it, were you unable to make a PR there for some reason? At any rate I should be able to download the files regardless.

tML update should have minimal breakage, only like two of my mods should be impacted, and one isn't releasing until after the October update.

**Comment by urgiv** [comment]
oh, there is already a GitHub page, I only checked the workshop page before localization work, so I missed it.

**Comment by BlockCrusader** [comment]
It's all good. I just released the update with the localization.

**Comment by urgiv** [comment]
Localization for Item Restriction Challenge
https://github.com/urgiv/zh-Hans-localization-files-for-1.4.4-mods/commit/c0c72ca4527b79a6eeafd37d9694bb2f155e7f8e

**Pull request merged**
